name: Test

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Deploy with rsync
        run: rsync -avz ./src/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/layeredApi/src/
  
