name: Test And Merge

on:
  pull_request:
    branches:
    - master
    - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
      
  auto_merge:
    name: auto_merge
    if: github.event.pull_request.mergeable_state == 'clean'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/auto_merge
  
